# Generated by Django 3.1.1 on 2020-09-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0004_auto_20200925_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
