# Generated by Django 3.1.1 on 2020-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0007_auto_20200925_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simmetexon'), (1, 'Diorganotis')], default=0),
        ),
    ]
