# Generated by Django 3.1.1 on 2020-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0008_auto_20200925_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('Tournament_Type', models.CharField(choices=[('Sports', 'Sports'), ('eSports', 'e-Sports'), ('Card_Games', 'Card Games')], default='Sports', max_length=30)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
