# Generated by Django 3.1.1 on 2020-09-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0009_tournaments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
