# Generated by Django 3.1.1 on 2020-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0010_auto_20200926_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='Prize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='regPrice',
            field=models.FloatField(null=True),
        ),
    ]
