# Generated by Django 3.1.1 on 2020-09-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0012_tournament_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
    ]
