# Generated by Django 3.1.1 on 2020-09-27 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0013_tournament_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
