# Generated by Django 3.1.1 on 2020-09-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0015_simmetoxes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simmetoxes',
            new_name='Simmetoxi',
        ),
    ]
