# Generated by Django 3.1.1 on 2020-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0017_simmetoxi_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmetoxi',
            name='name',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simmetoxi',
            name='teamName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
