# Generated by Django 3.1.1 on 2020-09-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0018_auto_20200928_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simmetoxi',
            old_name='name',
            new_name='phone',
        ),
    ]
