# Generated by Django 3.1.1 on 2020-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0019_auto_20200928_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simmetoxi',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
