# Generated by Django 3.1.1 on 2020-10-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0020_auto_20200928_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='PpT',
            field=models.IntegerField(null=True),
        ),
    ]
