# Generated by Django 3.1.1 on 2020-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0021_auto_20201006_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
