# Generated by Django 3.1.1 on 2020-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0022_auto_20201007_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
    ]
