# Generated by Django 3.1.1 on 2020-10-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createT', '0024_auto_20201007_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='date_end',
            new_name='dateEnd',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='date_start',
            new_name='dateStart',
        ),
    ]
